<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../../../favicon.ico"> -->

    <title>Redweb - Mince Pie Ratings</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <style type="text/css">
      .jumbotron {
        background-color: #e74c3c;
      }
      .display-3, .lead {
        color: #FFF;
      }
    </style>

  </head>

  <body>

    <div class="container">
      <main role="main">

        <div class="jumbotron">
          <div class="container">
            <div class="row">
              <div class="col-lg-8">
                <h1 class="display-3">Mince Pie Ratings</h1>
                <p class="lead">A team of industry leading experts (although the industry is not in anyway related to food production or critiquing) have been reviewing a range of mince pies and this website is the result of those, in no way scientific or possibly even accurate, reviews.</p>
              </div>
              <div class="col-lg-4">
                <img class="img-fluid" src="<?=$profile_pic?>">
              </div>
            </div>
          </div>
        </div>

        <div class="row marketing">
          <div class="col-lg-12">
            <h4>Results</h4>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Pie</th>
                  <th scope="col">Rating</th>
                </tr>
              </thead>
              <tbody>
            <?php foreach($pies as $pie): ?>                       
                <tr>
                  <td><?=$pie['name']; ?></td>
                  <td><?=$pie['averages']['non_rounded_rating']; ?></td>
                </tr>
            <?php endforeach; ?>                       
              </tbody>
            </table>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <?php foreach($instagram as $image): ?>                       
            <div class="col col-lg-4">
              <img src="<?=$image['image']?>" alt="<?=$image['caption']?>" class="img-fluid" style="padding-bottom: 20px;">
            </div>
            <?php endforeach; ?>              
          </div>
        </div>
      </main>

<!--       <footer class="footer">
        <p>&copy; Company 2017</p>
      </footer> -->
<!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110154461-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-110154461-1');
    </script>

    </div> <!-- /container -->
  </body>
</html>
